# Generated by Django 4.0.4 on 2022-11-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=24, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=24, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=60, verbose_name='Email')),
                ('contraseña', models.CharField(max_length=24, verbose_name='Contraseña')),
            ],
        ),
    ]
